
# Conclusion 

With the information given, we were unable to provide enough evidence that animated graphics increase the effectiveness of email-based event recruitment at Yale. Regardless of which treatment was assigned to the subjects, it does not look like animated graphics had a significant effect on recruitment/RSVPS. 

The experiment had many limitations, some of which were out of our control. Yale Students for Civic Engagement was a random club that nobody has heard of. We didn’t have any name recognition prior to the emails that we sent to first years in late October; thus, many students were probably not interested in other club activities. Also, with clubs such as Yale democrats, the federalist party, and the centrist party being popular on Yale’s campus, our club’s topic of civic engagement may have been redundant or not engaging to first years. If we were to repeat this experiment again, we would have established the club around the time students were looking to join clubs  earlier in the fall to make our experiment “more fieldy”.


