---
title: "Results"
author: "nathan"
date: "11/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(tidyverse)
library(here)
library(cowplot)
library(stargazer)
library(showtext)
library(chimpr) #from https://github.com/sckott/chimpr (use devtools::install_github("sckott/chimpr"))
#our mailchimp API key is stored on nathan's (personal) pc, aka outside of the repo
chimp_key <- Sys.getenv("MAILCHIMP_KEY")

font_add_google("Lato")
showtext_auto()
showtext_opts(dpi = 300)

theme_lato <- function(base_family = "Lato", base_size = 12, ...) {
  hrbrthemes::theme_ipsum_rc(base_family = "Lato") + 
    theme(axis.title.x = element_text(hjust = 0.5), 
          axis.title.y = element_text(vjust = .5))
}

theme_set(theme_lato())
update_geom_defaults("text", list(family = "Lato", fontface = "bold"))
```


```{r import}
conn <- ChmpClient$new(dc = "us2", key = chimp_key)
id_vec <- ChmpReports$new(conn)
id_vec <- id_vec$all()$reports$id
campaign_info <- ChmpCampaigns$new(conn)$all()$campaigns %>% 
  mutate(send_time = anytime::anytime(send_time),
         openrate = .$report_summary$open_rate,
         clicks = .$report_summary$click_rate) %>% 
  select(id, send_time, openrate, clicks) 

reports <- map_dfr(id_vec, function(report_id){
  report <- ChmpReports$new(conn, id = report_id)
  report_tbl <- report$open_details(count = 1000)$members %>% 
    mutate(info = report$info()$campaign_title)
  return(report_tbl)
})

reports <- reports %>% 
  group_by(info) %>% 
  left_join(campaign_info, by = c("campaign_id" = "id")) %>% 
  mutate(first_open_time =unlist(map(opens, function(x) x[1,])),
         first_open_time = anytime::anytime(first_open_time),
         time_diff = first_open_time - send_time,
         grp =  str_remove_all(info, "( - Election Day)") %>% 
           str_replace("_", " ") %>% 
           str_to_title(),
         grp = as_factor(grp) %>% 
           fct_recode( "Control (No animation)" = "Control",
                       "Animated Bar, Static Line" = "Treat 1",
                       "Static Bar, Animated Line" = "Treat 2",
                       "Both Animated" = "Treat 3"),
         set = ifelse(str_detect(info, "Election"), "Follow-up", "Initial")) %>% 
  arrange(info, time_diff) %>% 
  mutate(counter = 1:n())

maxes <- reports %>% 
  group_by(grp, set) %>% 
  top_n(1, wt = time_diff) %>% 
  mutate(time_diff = as.difftime(4000, units = "mins")) %>% 
  select(grp,set,counter, time_diff)

reports <- reports %>% bind_rows(maxes)
         # first_open_time = first_open_time %>% 
         #   str_replace("T", " ") %>% 
         #   str_remove("\\+00\\:00"))

```


```{r cumulative_opens, width = 8, height =5}

cumu_opens <- reports %>% 
  ggplot(aes(x = time_diff, y = counter, color = grp, linetype = set)) + 
  geom_line(size = 1) +
  scale_x_continuous(limits  = c(NA, 4000)) + 
  scale_y_continuous(limits = c(100, 305)) + 
  labs(y = "Opens", x = "Minutes since email was sent", 
       title = "Tracking email open rates across our campaigns",
       color = NULL, linetype = NULL) 
cumu_opens
ggsave(here("figures/opens.png"), cumu_opens, width  =8, height = 5) 

```


```{r summary_table, results = "asis"}

second_opens <- reports %>% 
  group_by(set, grp) %>% 
  summarize(open_freq = mean(opens_count > 1, na.rm=T))


fills <- c(4,1,2,2,2,1,3,1,1,2)
rates <-  table(fills)/table(reports$merge_fields$MMERGE7 )
rates <- tibble(set = "Initial", grp = unique(second_opens$grp), `Form Fills` = as.numeric(rates)) 

clicks <- reports %>% drop_na(time_diff,clicks) %>% 
  group_by(set,grp) %>% 
  top_n(1, wt = time_diff) %>% 
  select(clicks) %>% 
  full_join(rates, by = c("set","grp"))

full_join(second_opens, clicks, by = c("set","grp")) %>% 
  mutate(across(where(is.numeric), ~ifelse(is.na(.), NA_character_, paste0(round(.*100,2), "%")))) %>% 
  rename(Set= set, `Treatment Group` = grp,
         `Opened email a second time` = open_freq,
         `Form click rate` = clicks) %>% 
  stargazer(summary = F, header = F, 
            title = "Summary of Response Statistics Across Groups")

```


```{r summary_chart}
summary_chart <- full_join(second_opens, clicks, by = c("set","grp")) %>% 
  rename(Set= set, `Treatment Group` = grp,
         `Opened email a second time` = open_freq,
         `Form click rate` = clicks) %>% 
  filter(Set == "Follow-up") %>% 
  pivot_longer(cols = c(`Opened email a second time`, `Form click rate`, `Form Fills`)) %>% 
  ggplot(aes(fill = `Treatment Group`, x = name, y = value)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  labs(fill = NULL, y = "Rate", x = NULL,
       title = "Summary statistics of response variables")
ggsave(here("figures/summary_chart.png"), summary_chart, width  =8, height = 5) 

```

```{r t_test, results = "asis"}

#i can't figure out how to do this the "right" way but this hacks it well enough for our presentation
rates <- rates %>% 
  mutate(n = table(reports$merge_fields$MMERGE7)) 

dta <- tibble(id = unlist(map2(unique(rates$grp), rates$n, function(x,y) rep(x,y)))) %>% 
  group_by(id) %>% 
  mutate(counter = 1:n()) %>% 
  group_split() %>% 
  map2_dfr(c(4,4,1,1), function(x,y) mutate(x, filled = ifelse(counter <=y, 1, 0)))

pairwise.t.test(dta$filled, dta$id, p.adjust.method = "bonf")$p.value %>% 
  as_tibble(rownames = "Comparison Group") %>% 
  mutate(across(where(is.numeric), ~round(., 3))) %>% 
  stargazer(header = F, summary = F,
            title = "Pairwise comparisons using t-tests, pooled SD, and Bonferroni corrections")


```